### ISSUE TITLE
shortcut 'p' (swap scaling algorithm) does not work in Firefox ESR

### ISSUE THREAD

**Issue by ArloJamesBarnes** [Deathamns/Viewhance#52]
console gives an error ```Error in parsing value for ‘image-rendering’.  Declaration dropped.``` and then links to the inline CSS, duplicated below; I don't see an ```image-rendering``` statement in it.

```css
html, body {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  font: 12px "Trebuchet MS", sans-serif;
  cursor: default;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
}

#media {
  display: block;
  box-sizing: border-box;
  max-width: none;
  max-height: none;
  position: absolute;
  margin: 0;
  background-clip: padding-box;
  image-orientation: from-image;
}

html.audio #media {
  box-sizing: inherit;
  width: 50%;
  height: 40px !important;
  min-width: 300px;
  max-width: 1000px;
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  box-shadow: none;
  background: transparent;
}

html.load-failed #media {
  left: 50%;
  margin: 10% auto 0 -25%;
  padding: 10px;
  max-width: 50%;
  box-shadow: 0 0 5px red;
  text-align: center;
  font-size: 20px;
}

html.fullscreen #media {
  background: black !important;
}

#media:-moz-full-screen {
  background: black !important;
}

a {
  text-decoration: none;
}

:focus {
  outline: 0;
}

:invalid {
  box-shadow: none;
}

#menu {
  display: flex;
  position: fixed;
  top: 0;
}

#menu:not(.permanent) {
  opacity: 0;
  transition: opacity .15s, left .2s;
}

ul {
  display: inline-block;
  margin: 0;padding: 8px 0;
  background: rgba(0, 0, 0, .6);
  color: #fff;
  font-size: 25px;
  font-weight: 700;
  text-align: center;
  list-style: none;
}

li {
  position: relative;
  display: block;
  padding: 4px 15px;
  min-width: 25px;
  min-height: 25px;
  line-height: 100%;
}

li > svg > use {
  pointer-events: none;
}

li > svg {
  width: 25px;
  height: 25px;
  cursor: pointer;
  fill: rgba(0,0,0,0);
  stroke: #fff;
  color: #fff;
  transition: opacity .2s;
}

li > svg:hover {
  opacity: .6;
}

li ul {
  visibility: hidden;
  position: absolute;
  top: 0;
  left: 100%;
  text-align: left;
  opacity: 0;
}

li:hover ul {
  display: block;
  visibility: visible;
  opacity: 1;
  transition: visibility .4s, opacity .2s .3s;
}

li ul > li {
  display: block !important;
  font-size: 15px;
}

.send-hosts li > a {
  padding-bottom: 3px;
  padding-left: 25px;
  background-size: 16px 16px;
  background-repeat: no-repeat;
  background-position: 0 3px;
  color: #fff;
  cursor: pointer;
}

#menu > ul > li:hover, .send-hosts li > a:hover {
  color: silver;
}

input[type="range"] {
  width: 125px;
  vertical-align: middle;
}

li ul > li {
  white-space: nowrap;
}

.filters > ul {
  font-size: 15px;
}

.filters > form {
  margin: 0;
  padding: 0;
}

body.frames {
  overflow-y: scroll !important;
  text-align: center;
}

body.frames > div {
  width: 100%;
  height: 100%;
  box-sizing: border-box;
  padding: 10px;
}

#top-panel {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  padding: 10px;
  background-image: linear-gradient(to bottom, #fff, #ddd);
  box-shadow: 0 0 15px rgba(0, 0, 0, .4);
}

#frames {
  margin: 50px 0 5px;
}

#frames > canvas, #frames > img {
  margin: 2px;
}

#frames > .highlighted {
  outline: 2px solid #00a1ff;
}

#frames > canvas, #frames > img {
  display: none;
}

#current-frame + output {
  display: inline-block;
  width: 77px;
  font-family: Conoslas, monospace;
  text-align: right;
}

.back {
  font-size: 150%;
  text-decoration: none;
  color: black;
}

#frames.showall > img, #frames.showall > canvas {
  display: inline-block !important;
}

.partial-frame:hover {
  outline: 1px dotted #666;
}

/* Below lies user-specified styles */

body {
  background: silver;
  overflow: hidden;
}

#media {
  background: #fafafa;
  box-shadow: 0 0 5px grey;
}
```
